# -*- coding: utf-8 -*-
"""data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b9tAZgo2PMOilzIM8kg4TdjljgcGZ8aB
"""

import pandas as pd

# 1. Load the datasets
print("Loading datasets...")
qs_data = pd.read_csv('qs-world-rankings-2025.csv')
the_data = pd.read_csv('THE World University Rankings 2016-2026.csv')

# 2. Filter THE dataset for the year 2025 to match QS 2025
the_2025 = the_data[the_data['Year'] == 2025].copy()

# 3. Create a basic name standardization function to help merge the datasets
def simplify_name(name):
    if pd.isna(name): return ""
    return str(name).lower().replace("the ", "").replace("university of ", "").replace(" university", "").strip()

qs_data['Join_Name'] = qs_data['Institution Name'].apply(simplify_name)
the_2025['Join_Name'] = the_2025['Name'].apply(simplify_name)

# 4. Merge datasets into a common structure
print("Merging datasets...")
raw_data = pd.merge(qs_data, the_2025, on='Join_Name', how='outer', suffixes=('_QS', '_THE'))

# 5. Save the raw merged data as required by the project deliverable
raw_data.to_csv('university_raw_data.csv', index=False)
print("Module 1 Complete: 'university_raw_data.csv' saved successfully!")

# 1. Load the raw data we just created
df = pd.read_csv('university_raw_data.csv')
print("Starting data cleaning...")

# 2. Remove duplicates
df = df.drop_duplicates()

# 3. Standardize University Names (If QS has a name, use it; otherwise use THE name)
df['University_Name'] = df['Institution Name'].fillna(df['Name'])

# 4. Standardize Country Names
df['Country_Clean'] = df['Location Full'].fillna(df['Country'])
df['Country_Clean'] = df['Country_Clean'].replace({'US': 'United States', 'UK': 'United Kingdom'})

# 5. Handle missing values to get them under 2%
# Fill empty numbers with 0
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].fillna(0)

# Fill empty text with 'Unknown'
string_cols = df.select_dtypes(include=['object']).columns
df[string_cols] = df[string_cols].fillna('Unknown')

# 6. Select and rename columns to create a normalized, Tableau-ready dataset
tableau_ready_df = df[[
    'University_Name', 'Country_Clean', '2025 Rank', 'Rank',
    'QS Overall Score', 'Overall Score', 'Academic Reputation',
    'Employer Reputation', 'International Students_QS', 'International Students_THE'
]].copy()

# Rename columns to be neat and consistent
tableau_ready_df.columns = [
    'University Name', 'Country', 'QS Rank', 'THE Rank',
    'QS Score', 'THE Score', 'Academic Reputation',
    'Employer Reputation', 'International Students % (QS)', 'International Students % (THE)'
]

# 7. Save the cleaned data
tableau_ready_df.to_csv('university_cleaned.csv', index=False)
print("Module 2 Complete: 'university_cleaned.csv' saved successfully!")



