# -*- coding: utf-8 -*-
"""generate_education_kpis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18O0pl38Uhx8ImF1pLo0zO-zaxwMeHlDF
"""

import pandas as pd
import numpy as np

print("Loading raw data for KPI Engineering...")
# Load the raw dataset that contains all the original metrics
df = pd.read_csv('university_raw_data.csv')

# Clean up numeric columns to ensure our math works
cols_to_clean = ['QS Overall Score', 'Overall Score', 'Citations per Faculty', 'Research Quality',
                 'Faculty Student', 'International Students_QS', 'Academic Reputation', 'International Research Network']

for col in cols_to_clean:
    if col in df.columns:
        # Convert to numeric, replacing any errors or text with 0
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

print("Calculating the 6 required KPIs...")

# 1. Global Ranking Score (Average of QS and THE overall scores)
df['Global Ranking Score'] = (df.get('QS Overall Score', 0) + df.get('Overall Score', 0)) / 2

# 2. Research Impact Score (Average of QS Citations and THE Research Quality)
df['Research Impact Score'] = (df.get('Citations per Faculty', 0) + df.get('Research Quality', 0)) / 2

# 3. Faculty-to-Student Ratio (Using QS standardized score)
df['Faculty-to-Student Ratio'] = df.get('Faculty Student', 0)

# 4. International Student Percentage (Using QS standardized score)
df['International Student Percentage'] = df.get('International Students_QS', 0)

# 5. Academic Reputation Score (Using QS metric directly)
df['Academic Reputation Score'] = df.get('Academic Reputation', 0)

# 6. Research Productivity Index (Using QS International Research Network)
df['Research Productivity Index'] = df.get('International Research Network', 0)

# Select the most important columns for our final Tableau dataset
final_columns = [
    'Institution Name', 'Location Full', '2025 Rank',
    'Global Ranking Score', 'Research Impact Score',
    'Faculty-to-Student Ratio', 'International Student Percentage',
    'Academic Reputation Score', 'Research Productivity Index'
]

# Filter the dataset to only include these columns, and rename them to look clean
final_df = df[final_columns].copy()
final_df.columns = [
    'University Name', 'Country', 'World Rank',
    'Global Ranking Score', 'Research Impact Score',
    'Faculty-to-Student Ratio', 'International Student Percentage',
    'Academic Reputation Score', 'Research Productivity Index'
]

# Save as an Excel file, as required by the project deliverables
final_df.to_excel('university_final_dataset.xlsx', index=False)
print("Module 3 Complete: 'university_final_dataset.xlsx' saved successfully!")



